name: "lint"
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
